version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.0
  pre_build:
    commands:
      - echo Composer downloading packages
      - composer install --no-progress --ignore-platform-reqs
      - cp .env.example .env
      - php artisan key:generate
      - php artisan cache:clear
      - php artisan config:clear
      - php artisan passport:keys
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodejs -f docker/nodejs/Dockerfile .
      - docker run --rm -v $(pwd):/build -w /build nodejs npm install
      - docker run --rm -v $(pwd):/build -w /build nodejs npm run dev
      
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_PHP_FPM_NAME:latest -f docker/php-fpm/Dockerfile .
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_PHP_FPM_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_PHP_FPM_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_PHP_FPM_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_PHP_FPM_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NGINX_NAME:latest -f docker/nginx/Dockerfile .
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NGINX_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NGINX_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NGINX_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NGINX_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      # create new task definition
      - chmod +x ./create-new-task-def.sh
      - ./create-new-task-def.sh demo

artifacts:
  files:
    - 'appspec.yaml'
    - 'taskdef.json'