version: "3"
services:
    app:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        image: docker/laravel
        container_name: app
        tty: true
        restart: unless-stopped
        environment:
            DB_HOST: db
            DB_PASSWORD: passowrd
            SESSION_DRIVER: redis
            REDIS_HOST: redis
        volumes:
            - ./:/var/www
            - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db

    webserver:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: docker/nginx
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./config/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app

    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
    redis:
        image: redis:latest
        container_name: redis

volumes:
    dbdata:
        driver: local
