export const FETCH_GET_ALL_ADVERTISE_LOCATIONS = 'FETCH_GET_ALL_ADVERTISE_LOCATIONS';
export const GET_ONE_ADVERTISE_LECTURE_LIST = 'GET_ONE_ADVERTISE_LECTURE_LIST';
export const ADD_LECTURE_TO_ADVERTISE = 'ADD_LECTURE_TO_ADVERTISE';
export const DELETE_LECTURE_TO_ADVERTISE = 'DELETE_LECTURE_TO_ADVERTISE';